image: Visual Studio 2015
init:
  - git config --global core.autocrlf true
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - dotnet --version
  - dotnet restore
test:
  assemblies:
    - '**\*.tests.dll'