//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hWorkType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hWorkType()
        {
            this.jWorkList = new HashSet<jWorkList>();
        }
    
        public int WorkTypeId { get; set; }
        public string Description { get; set; }
        public int SkillId { get; set; }
    
        public virtual hSkill hSkill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jWorkList> jWorkList { get; set; }
    }
}
