//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class jJournal
{
    public System.DateTime Date { get; set; }
    public int EventTypeId { get; set; }
    public int WorkListId { get; set; }
    public string Description { get; set; }
    public int JournalId { get; set; }
    public string PersonId { get; set; }

    public virtual hEventType hEventType { get; set; }
    public virtual AspNetUsers AspNetUsers { get; set; }
    public virtual jWorkList jWorkList { get; set; }
}
